#:schema node_modules/wrangler/config-schema.json

name = "lianyu-ai"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

# HTML 文件作为模块导入
rules = [
  { type = "Text", globs = ["**/*.html"], fallthrough = true }
]

# 环境变量（可选，也可以在 Cloudflare Dashboard 中设置）
# [vars]
# AI_API_KEY = "sk-xxxxxx"



routes = [
  { pattern = "lianyuai.jia56ju.online", custom_domain = true }
]
